// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/messages.proto

package dev.yanshouwang.bluetooth_low_energy.proto;

public interface AdvertisementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Advertisement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Peripheral peripheral = 1;</code>
   * @return Whether the peripheral field is set.
   */
  boolean hasPeripheral();
  /**
   * <code>.proto.Peripheral peripheral = 1;</code>
   * @return The peripheral.
   */
  dev.yanshouwang.bluetooth_low_energy.proto.Peripheral getPeripheral();
  /**
   * <code>.proto.Peripheral peripheral = 1;</code>
   */
  dev.yanshouwang.bluetooth_low_energy.proto.PeripheralOrBuilder getPeripheralOrBuilder();

  /**
   * <code>map&lt;int32, bytes&gt; data = 2;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;int32, bytes&gt; data = 2;</code>
   */
  boolean containsData(
      int key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
  getData();
  /**
   * <code>map&lt;int32, bytes&gt; data = 2;</code>
   */
  java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
  getDataMap();
  /**
   * <code>map&lt;int32, bytes&gt; data = 2;</code>
   */

  /* nullable */
com.google.protobuf.ByteString getDataOrDefault(
      int key,
      /* nullable */
com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;int32, bytes&gt; data = 2;</code>
   */

  com.google.protobuf.ByteString getDataOrThrow(
      int key);

  /**
   * <code>int32 rssi = 3;</code>
   * @return The rssi.
   */
  int getRssi();
}
