// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/messages.proto

package dev.yanshouwang.bluetooth_low_energy.proto;

public interface BroadcastOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Broadcast)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Peripheral peripheral = 1;</code>
   * @return Whether the peripheral field is set.
   */
  boolean hasPeripheral();
  /**
   * <code>.proto.Peripheral peripheral = 1;</code>
   * @return The peripheral.
   */
  dev.yanshouwang.bluetooth_low_energy.proto.Peripheral getPeripheral();
  /**
   * <code>.proto.Peripheral peripheral = 1;</code>
   */
  dev.yanshouwang.bluetooth_low_energy.proto.PeripheralOrBuilder getPeripheralOrBuilder();

  /**
   * <code>int32 rssi = 2;</code>
   * @return The rssi.
   */
  int getRssi();

  /**
   * <code>optional bool connectable = 3;</code>
   * @return Whether the connectable field is set.
   */
  boolean hasConnectable();
  /**
   * <code>optional bool connectable = 3;</code>
   * @return The connectable.
   */
  boolean getConnectable();

  /**
   * <code>bytes data = 4;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>optional string local_name = 5;</code>
   * @return Whether the localName field is set.
   */
  boolean hasLocalName();
  /**
   * <code>optional string local_name = 5;</code>
   * @return The localName.
   */
  java.lang.String getLocalName();
  /**
   * <code>optional string local_name = 5;</code>
   * @return The bytes for localName.
   */
  com.google.protobuf.ByteString
      getLocalNameBytes();

  /**
   * <code>bytes manufacturer_specific_data = 6;</code>
   * @return The manufacturerSpecificData.
   */
  com.google.protobuf.ByteString getManufacturerSpecificData();

  /**
   * <code>repeated .proto.ServiceData service_datas = 7;</code>
   */
  java.util.List<dev.yanshouwang.bluetooth_low_energy.proto.ServiceData> 
      getServiceDatasList();
  /**
   * <code>repeated .proto.ServiceData service_datas = 7;</code>
   */
  dev.yanshouwang.bluetooth_low_energy.proto.ServiceData getServiceDatas(int index);
  /**
   * <code>repeated .proto.ServiceData service_datas = 7;</code>
   */
  int getServiceDatasCount();
  /**
   * <code>repeated .proto.ServiceData service_datas = 7;</code>
   */
  java.util.List<? extends dev.yanshouwang.bluetooth_low_energy.proto.ServiceDataOrBuilder> 
      getServiceDatasOrBuilderList();
  /**
   * <code>repeated .proto.ServiceData service_datas = 7;</code>
   */
  dev.yanshouwang.bluetooth_low_energy.proto.ServiceDataOrBuilder getServiceDatasOrBuilder(
      int index);

  /**
   * <code>repeated .proto.UUID service_uuids = 8;</code>
   */
  java.util.List<dev.yanshouwang.bluetooth_low_energy.proto.UUID> 
      getServiceUuidsList();
  /**
   * <code>repeated .proto.UUID service_uuids = 8;</code>
   */
  dev.yanshouwang.bluetooth_low_energy.proto.UUID getServiceUuids(int index);
  /**
   * <code>repeated .proto.UUID service_uuids = 8;</code>
   */
  int getServiceUuidsCount();
  /**
   * <code>repeated .proto.UUID service_uuids = 8;</code>
   */
  java.util.List<? extends dev.yanshouwang.bluetooth_low_energy.proto.UUIDOrBuilder> 
      getServiceUuidsOrBuilderList();
  /**
   * <code>repeated .proto.UUID service_uuids = 8;</code>
   */
  dev.yanshouwang.bluetooth_low_energy.proto.UUIDOrBuilder getServiceUuidsOrBuilder(
      int index);

  /**
   * <code>repeated .proto.UUID solicited_service_uuids = 9;</code>
   */
  java.util.List<dev.yanshouwang.bluetooth_low_energy.proto.UUID> 
      getSolicitedServiceUuidsList();
  /**
   * <code>repeated .proto.UUID solicited_service_uuids = 9;</code>
   */
  dev.yanshouwang.bluetooth_low_energy.proto.UUID getSolicitedServiceUuids(int index);
  /**
   * <code>repeated .proto.UUID solicited_service_uuids = 9;</code>
   */
  int getSolicitedServiceUuidsCount();
  /**
   * <code>repeated .proto.UUID solicited_service_uuids = 9;</code>
   */
  java.util.List<? extends dev.yanshouwang.bluetooth_low_energy.proto.UUIDOrBuilder> 
      getSolicitedServiceUuidsOrBuilderList();
  /**
   * <code>repeated .proto.UUID solicited_service_uuids = 9;</code>
   */
  dev.yanshouwang.bluetooth_low_energy.proto.UUIDOrBuilder getSolicitedServiceUuidsOrBuilder(
      int index);

  /**
   * <code>optional int32 tx_power_level = 10;</code>
   * @return Whether the txPowerLevel field is set.
   */
  boolean hasTxPowerLevel();
  /**
   * <code>optional int32 tx_power_level = 10;</code>
   * @return The txPowerLevel.
   */
  int getTxPowerLevel();
}
