//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.bluetooth_low_energy;

@kotlin.jvm.JvmSynthetic
public inline fun centralConnectCommand(block: dev.yanshouwang.bluetooth_low_energy.CentralConnectCommandKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.bluetooth_low_energy.Messages.CentralConnectCommand =
  dev.yanshouwang.bluetooth_low_energy.CentralConnectCommandKt.Dsl._create(dev.yanshouwang.bluetooth_low_energy.Messages.CentralConnectCommand.newBuilder()).apply { block() }._build()
public object CentralConnectCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.yanshouwang.bluetooth_low_energy.Messages.CentralConnectCommand.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.bluetooth_low_energy.Messages.CentralConnectCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.bluetooth_low_energy.Messages.CentralConnectCommand = _builder.build()

    /**
     * <code>string uuid = 1;</code>
     */
    public var uuid: kotlin.String
      @JvmName("getUuid")
      get() = _builder.getUuid()
      @JvmName("setUuid")
      set(value) {
        _builder.setUuid(value)
      }
    /**
     * <code>string uuid = 1;</code>
     */
    public fun clearUuid() {
      _builder.clearUuid()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.yanshouwang.bluetooth_low_energy.Messages.CentralConnectCommand.copy(block: dev.yanshouwang.bluetooth_low_energy.CentralConnectCommandKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.bluetooth_low_energy.Messages.CentralConnectCommand =
  dev.yanshouwang.bluetooth_low_energy.CentralConnectCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()
