//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.bluetooth_low_energy;

@kotlin.jvm.JvmSynthetic
public inline fun gattService(block: dev.yanshouwang.bluetooth_low_energy.GattServiceKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.bluetooth_low_energy.Messages.GattService =
  dev.yanshouwang.bluetooth_low_energy.GattServiceKt.Dsl._create(dev.yanshouwang.bluetooth_low_energy.Messages.GattService.newBuilder()).apply { block() }._build()
public object GattServiceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.yanshouwang.bluetooth_low_energy.Messages.GattService.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.bluetooth_low_energy.Messages.GattService.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.bluetooth_low_energy.Messages.GattService = _builder.build()

    /**
     * <code>string indexed_uuid = 1;</code>
     */
    public var indexedUuid: kotlin.String
      @JvmName("getIndexedUuid")
      get() = _builder.getIndexedUuid()
      @JvmName("setIndexedUuid")
      set(value) {
        _builder.setIndexedUuid(value)
      }
    /**
     * <code>string indexed_uuid = 1;</code>
     */
    public fun clearIndexedUuid() {
      _builder.clearIndexedUuid()
    }

    /**
     * <code>string uuid = 2;</code>
     */
    public var uuid: kotlin.String
      @JvmName("getUuid")
      get() = _builder.getUuid()
      @JvmName("setUuid")
      set(value) {
        _builder.setUuid(value)
      }
    /**
     * <code>string uuid = 2;</code>
     */
    public fun clearUuid() {
      _builder.clearUuid()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CharacteristicsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .dev.yanshouwang.bluetooth_low_energy.GattCharacteristic characteristics = 3;</code>
     */
     public val characteristics: com.google.protobuf.kotlin.DslList<dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic, CharacteristicsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getCharacteristicsList()
      )
    /**
     * <code>repeated .dev.yanshouwang.bluetooth_low_energy.GattCharacteristic characteristics = 3;</code>
     * @param value The characteristics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCharacteristics")
    public fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic, CharacteristicsProxy>.add(value: dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic) {
      _builder.addCharacteristics(value)
    }/**
     * <code>repeated .dev.yanshouwang.bluetooth_low_energy.GattCharacteristic characteristics = 3;</code>
     * @param value The characteristics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCharacteristics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic, CharacteristicsProxy>.plusAssign(value: dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic) {
      add(value)
    }/**
     * <code>repeated .dev.yanshouwang.bluetooth_low_energy.GattCharacteristic characteristics = 3;</code>
     * @param values The characteristics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCharacteristics")
    public fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic, CharacteristicsProxy>.addAll(values: kotlin.collections.Iterable<dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic>) {
      _builder.addAllCharacteristics(values)
    }/**
     * <code>repeated .dev.yanshouwang.bluetooth_low_energy.GattCharacteristic characteristics = 3;</code>
     * @param values The characteristics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCharacteristics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic, CharacteristicsProxy>.plusAssign(values: kotlin.collections.Iterable<dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic>) {
      addAll(values)
    }/**
     * <code>repeated .dev.yanshouwang.bluetooth_low_energy.GattCharacteristic characteristics = 3;</code>
     * @param index The index to set the value at.
     * @param value The characteristics to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCharacteristics")
    public operator fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic, CharacteristicsProxy>.set(index: kotlin.Int, value: dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic) {
      _builder.setCharacteristics(index, value)
    }/**
     * <code>repeated .dev.yanshouwang.bluetooth_low_energy.GattCharacteristic characteristics = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCharacteristics")
    public fun com.google.protobuf.kotlin.DslList<dev.yanshouwang.bluetooth_low_energy.Messages.GattCharacteristic, CharacteristicsProxy>.clear() {
      _builder.clearCharacteristics()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.yanshouwang.bluetooth_low_energy.Messages.GattService.copy(block: dev.yanshouwang.bluetooth_low_energy.GattServiceKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.bluetooth_low_energy.Messages.GattService =
  dev.yanshouwang.bluetooth_low_energy.GattServiceKt.Dsl._create(this.toBuilder()).apply { block() }._build()
