// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.hebei.bluetooth_low_energy_android;

@kotlin.jvm.JvmName("-initializeadvertisementApi")
public inline fun advertisementApi(block: dev.hebei.bluetooth_low_energy_android.AdvertisementApiKt.Dsl.() -> kotlin.Unit): dev.hebei.bluetooth_low_energy_android.AdvertisementApi =
  dev.hebei.bluetooth_low_energy_android.AdvertisementApiKt.Dsl._create(dev.hebei.bluetooth_low_energy_android.AdvertisementApi.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `AdvertisementApi`
 */
public object AdvertisementApiKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.hebei.bluetooth_low_energy_android.AdvertisementApi.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.hebei.bluetooth_low_energy_android.AdvertisementApi.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.hebei.bluetooth_low_energy_android.AdvertisementApi = _builder.build()

    /**
     * `optional string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `optional string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * `optional string name = 1;`
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ServiceUuidsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string service_uuids = 2;`
     * @return A list containing the serviceUuids.
     */
    public val serviceUuids: com.google.protobuf.kotlin.DslList<kotlin.String, ServiceUuidsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.serviceUuidsList
      )
    /**
     * `repeated string service_uuids = 2;`
     * @param value The serviceUuids to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addServiceUuids")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ServiceUuidsProxy>.add(value: kotlin.String) {
      _builder.addServiceUuids(value)
    }
    /**
     * `repeated string service_uuids = 2;`
     * @param value The serviceUuids to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignServiceUuids")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ServiceUuidsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string service_uuids = 2;`
     * @param values The serviceUuids to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllServiceUuids")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ServiceUuidsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllServiceUuids(values)
    }
    /**
     * `repeated string service_uuids = 2;`
     * @param values The serviceUuids to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllServiceUuids")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ServiceUuidsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string service_uuids = 2;`
     * @param index The index to set the value at.
     * @param value The serviceUuids to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setServiceUuids")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ServiceUuidsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setServiceUuids(index, value)
    }/**
     * `repeated string service_uuids = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearServiceUuids")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ServiceUuidsProxy>.clear() {
      _builder.clearServiceUuids()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ServiceDataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, bytes> service_data = 3;`
     */
     public val serviceData: com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.ByteString, ServiceDataProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getServiceDataMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.serviceDataMap
      )
    /**
     * `map<string, bytes> service_data = 3;`
     */
    @JvmName("putServiceData")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.ByteString, ServiceDataProxy>
      .put(key: kotlin.String, value: com.google.protobuf.ByteString) {
         _builder.putServiceData(key, value)
       }
    /**
     * `map<string, bytes> service_data = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setServiceData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.ByteString, ServiceDataProxy>
      .set(key: kotlin.String, value: com.google.protobuf.ByteString) {
         put(key, value)
       }
    /**
     * `map<string, bytes> service_data = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeServiceData")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.ByteString, ServiceDataProxy>
      .remove(key: kotlin.String) {
         _builder.removeServiceData(key)
       }
    /**
     * `map<string, bytes> service_data = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllServiceData")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.ByteString, ServiceDataProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, com.google.protobuf.ByteString>) {
         _builder.putAllServiceData(map)
       }
    /**
     * `map<string, bytes> service_data = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearServiceData")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.ByteString, ServiceDataProxy>
      .clear() {
         _builder.clearServiceData()
       }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ManufacturerSpecificDataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ManufacturerSpecificDataApi manufacturer_specific_data = 4;`
     */
     public val manufacturerSpecificData: com.google.protobuf.kotlin.DslList<dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi, ManufacturerSpecificDataProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.manufacturerSpecificDataList
      )
    /**
     * `repeated .ManufacturerSpecificDataApi manufacturer_specific_data = 4;`
     * @param value The manufacturerSpecificData to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addManufacturerSpecificData")
    public fun com.google.protobuf.kotlin.DslList<dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi, ManufacturerSpecificDataProxy>.add(value: dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi) {
      _builder.addManufacturerSpecificData(value)
    }
    /**
     * `repeated .ManufacturerSpecificDataApi manufacturer_specific_data = 4;`
     * @param value The manufacturerSpecificData to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignManufacturerSpecificData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi, ManufacturerSpecificDataProxy>.plusAssign(value: dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi) {
      add(value)
    }
    /**
     * `repeated .ManufacturerSpecificDataApi manufacturer_specific_data = 4;`
     * @param values The manufacturerSpecificData to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllManufacturerSpecificData")
    public fun com.google.protobuf.kotlin.DslList<dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi, ManufacturerSpecificDataProxy>.addAll(values: kotlin.collections.Iterable<dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi>) {
      _builder.addAllManufacturerSpecificData(values)
    }
    /**
     * `repeated .ManufacturerSpecificDataApi manufacturer_specific_data = 4;`
     * @param values The manufacturerSpecificData to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllManufacturerSpecificData")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi, ManufacturerSpecificDataProxy>.plusAssign(values: kotlin.collections.Iterable<dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi>) {
      addAll(values)
    }
    /**
     * `repeated .ManufacturerSpecificDataApi manufacturer_specific_data = 4;`
     * @param index The index to set the value at.
     * @param value The manufacturerSpecificData to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setManufacturerSpecificData")
    public operator fun com.google.protobuf.kotlin.DslList<dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi, ManufacturerSpecificDataProxy>.set(index: kotlin.Int, value: dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi) {
      _builder.setManufacturerSpecificData(index, value)
    }
    /**
     * `repeated .ManufacturerSpecificDataApi manufacturer_specific_data = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearManufacturerSpecificData")
    public fun com.google.protobuf.kotlin.DslList<dev.hebei.bluetooth_low_energy_android.ManufacturerSpecificDataApi, ManufacturerSpecificDataProxy>.clear() {
      _builder.clearManufacturerSpecificData()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.hebei.bluetooth_low_energy_android.AdvertisementApi.copy(block: `dev.hebei.bluetooth_low_energy_android`.AdvertisementApiKt.Dsl.() -> kotlin.Unit): dev.hebei.bluetooth_low_energy_android.AdvertisementApi =
  `dev.hebei.bluetooth_low_energy_android`.AdvertisementApiKt.Dsl._create(this.toBuilder()).apply { block() }._build()

