name: bluetooth_low_energy_core
description: A bluetooth low energy plugin for flutter, which can be used to develope central role apps.
version: 0.0.1
homepage: "https://github.com/yanshouwang/bluetooth_low_energy"

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  protobuf: ^2.1.0
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^4.0.2
